# Generated by Django 3.2.9 on 2022-02-04 07:38

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t002parents',
            name='notification',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='ログイン時に必須', max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='01', error_messages={'unique': 'A user with that username already exists.'}, help_text='ユーザ名は名前をローマ字で入力してください。この項目は必須です。', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='t002parents',
            name='user',
            field=models.OneToOneField(help_text='登録したユーザ名を選択', on_delete=django.db.models.deletion.CASCADE, related_name='detail_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t003childminder',
            name='user',
            field=models.OneToOneField(help_text='登録したユーザ名を選択', on_delete=django.db.models.deletion.CASCADE, related_name='detail_buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
